# Generated by Django 2.1.14 on 2020-04-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_device_transission_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='transission_rate',
            new_name='transmission_rate',
        ),
    ]
