# Generated by Django 2.1 on 2020-04-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200420_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmission',
            name='flowrate',
            field=models.IntegerField(choices=[(0, 'Posible Clog'), (1, 'Normal'), (2, 'High')]),
        ),
    ]
